docker-deploy/web-app/ride_sharing/urls.py
from django.urls import path

from . import views

app_name = "ride_sharing"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    #path("send_email_test/", views.send_email_test, name="send_email_test"),
    path("user_register/", views.user_register, name="user_register"),
    # user request related
    path("place_request/", views.place_request, name="place_request"),
    path("my_requests/", views.my_requests, name="my_requests"),
    path("view_request_detail", views.view_request_detail, name="view_request_detail"),
    path("edit_request_detail_owner", views.edit_request_detail_owner, name="edit_request_detail_owner"),
    path("edit_request_detail_sharer", views.edit_request_detail_sharer, name="edit_request_detail_sharer"),
    # driver related
    path("driver_view_confirmed_requests/", views.driver_view_confirmed_requests, name="driver_view_confirmed_requests"),
    path("driver_registration/", views.driver_registration, name="driver_registration"),
    path("driver_profile/", views.driver_profile, name="driver_profile"),
    path("edit_driver_profile/", views.edit_driver_profile, name="edit_driver_profile"),
    path("driver_registration_result/", views.driver_registration_result, name="driver_registration_result"),
    path("driver_search_for_open_request/", views.driver_search_for_open_request, name="driver_search_for_open_request"),
    # sharer related
    path("sharer_search_for_open_request/", views.sharer_search_for_open_request, name="sharer_search_for_open_request"),
]

docker-deploy/web-app/rideshare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("ride_sharing/", include("ride_sharing.urls")),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name="ride_sharing/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="ride_sharing/logout.html"), name="logout"),
]

docker-deploy/web-app/ride_sharing/models.py
import datetime

from django.conf import settings
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User

# Create your models here.
# class User(models.Model):
#     # email = models.CharField(max_length=200)
#     registration_date = models.DateTimeField("date registered")
#     def __str__(self):
#         return str(self.id)

class Driver(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    vehicle_type = models.CharField(max_length=200)
    license_plate_num = models.CharField(max_length=50)
    max_passenger_num = models.IntegerField()
    special_vehicle_info = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.name
    
class Request(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, models.SET_NULL, blank=True, null=True)
    destination = models.CharField(max_length=200)
    expected_arrival_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    num_passengers = models.IntegerField(default=1)
    vehicle_type = models.CharField(max_length=200, blank=True)
    special_request = models.TextField(blank=True)
    can_share = models.BooleanField()
    is_open = models.BooleanField()
    is_complete = models.BooleanField()
    def __str__(self):
        return self.destination

class ShareRide(models.Model):
    sharer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    booking = models.ForeignKey(Request, on_delete=models.CASCADE)
    num_sharer = models.IntegerField(default=1)
    def __str__(self):
        return self.sharer.username

docker-deploy/web-app/ride_sharing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

docker-deploy/web-app/ride_sharing/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum, Max
from django.core.mail import send_mail

from .forms import UserRegistrationForm
from .models import Driver, Request, ShareRide #, User 

@login_required
def homepage(request):
    return render(request, "ride_sharing/homepage.html")
    #return HttpResponse("Welcome to the ride sharing service! Click on the menu bar to continue")

def user_register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account Created for {username}. You can now log in")
            return redirect("login")
    else:   
        form = UserRegistrationForm()
    return render(request, "ride_sharing/user_register.html", {"form": form})

# @login_required
# def send_email(request):
#     send_mail(
#     "Subject here",
#     "Here is the message.",
#     "yhece568@yahoo.com",
#     ["aybucydu9@gmail.com"],
#     fail_silently=False,)
#     return HttpResponse("successfully sent email")
#    return render(request, "ride_sharing/place_request.html")

@login_required
def place_request(request):
    return render(request, "ride_sharing/place_request.html")

@login_required
def my_requests(request):
    if request.method == "POST":
        # sharer join a shared ride
        if request.POST.get("request_id_sharer_join"):
            try:
                existing_shareride = ShareRide.objects.get(sharer=request.user, booking=Request.objects.get(pk = int(request.POST["request_id_sharer_join"])))
                messages.error(request, f"You have already shared this ride before and can not join again. If you want to update your share request, please use the edit function!")
            except (KeyError, ShareRide.DoesNotExist):
                new_shareride = ShareRide(
                            sharer=request.user,
                            booking=Request.objects.get(pk = int(request.POST["request_id_sharer_join"])), 
                            num_sharer = request.POST["num_sharer"]
                            )
                new_shareride.save()
                share_destination = Request.objects.get(pk = int(request.POST["request_id_sharer_join"])).destination
                messages.success(request, f"Your Have successfully joined the shared ride to {share_destination}")

        # sharer cancle a shared ride    
        elif request.POST.get("cancel_ride_sharer"):
            shareride_to_delete = ShareRide.objects.get(booking=request.POST["cancel_ride_sharer"], sharer=request.user)
            shareride_to_delete.delete()
        
        # owner cancled a ride
        elif request.POST.get("cancel_ride"):
            request_to_delete = Request.objects.get(pk=request.POST["cancel_ride"])
            request_to_delete.delete()
        
        # place a new request
        else:
            # check input data validity
            if int(request.POST["num_passengers"]) < 1:
                messages.error(request, "Number of passenger can not be less than 1. Please correct your request info and place request again.")
                return render(request, "ride_sharing/place_request.html", {"current_data" : request.POST})
            elif int(request.POST["num_passengers"]) > 6:
                messages.error(request, "Number of passenger can not be more than 6. Please correct your request info and place request again.")
                return render(request, "ride_sharing/place_request.html", {"current_data" : request.POST})
            
            new_request = Request(owner=request.user, 
                            destination=request.POST["destination"], 
                            expected_arrival_time = request.POST["expected_arrival_time"],
                            num_passengers = request.POST["num_passengers"],
                            vehicle_type = request.POST["vehicle_type"],
                            special_request = request.POST["special_request"],
                            can_share = True if request.POST.get("can_share") == "on" else False,
                            is_open = True,
                            is_complete = False)
            new_request.save()
    
    # general - display request
    my_request_list = Request.objects.filter(owner=request.user) | Request.objects.filter(shareride__sharer=request.user)
    my_request_list = my_request_list.values("id", 
                                                "owner",
                                                "shareride__booking", 
                                                "destination", 
                                                "expected_arrival_time", 
                                                "num_passengers", 
                                                "can_share", 
                                                "is_open", 
                                                "is_complete").annotate(total_sharer = Sum("shareride__num_sharer"),
                                                                        total_pax = Sum("shareride__num_sharer") + Max("num_passengers"))
    my_request_list = my_request_list.exclude(is_complete=True).order_by("-expected_arrival_time")
    context = {"my_request_list": my_request_list, "cur_user": request.user}
    return render(request, "ride_sharing/my_requests.html", context)

@login_required
def view_request_detail(request):
    if request.method == "POST":
        # sharer edit ride details
        if request.POST.get("confirm_sharer"):
            if int(request.POST["num_sharer"]) < 1:
                messages.error(request, "Number of sharer can not be less than 1. Please correct your request info and place request again.")
                shareride_info = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user) 
                return render(request, "ride_sharing/edit_request_detail_sharer.html", 
                                        {"shareride_info": shareride_info,"current_data" : request.POST})
            elif int(request.POST["num_sharer"]) > 5:
                messages.error(request, "Number of sharer can not be more than 5. Please correct your request info and place request again.")
                shareride_info = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user) 
                return render(request, "ride_sharing/edit_request_detail_sharer.html", {"shareride_info": shareride_info,"current_data" : request.POST})

            shareride_to_update = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user)
            shareride_to_update.num_sharer = request.POST["num_sharer"]
            shareride_to_update.save()
            selected_request = Request.objects.get(pk=request.POST["confirm_sharer"])
        # owner edit ride details
        elif request.POST.get("confirm"):
            if int(request.POST["num_passengers"]) < 1:
                messages.error(request, "Number of passengers can not be less than 1. Please correct your request info and place request again.")
                request_info = Request.objects.get(pk=request.POST["confirm"])
                formatted_time = request.POST["expected_arrival_time"]
                return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time, "current_data" : request.POST})
                
            elif int(request.POST["num_passengers"]) > 6:
                messages.error(request, "Number of passengers can not be more than 6. Please correct your request info and place request again.")
                request_info = Request.objects.get(pk=request.POST["confirm"])
                formatted_time = request.POST["expected_arrival_time"]
                return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time, "current_data" : request.POST})

            request_to_update = Request.objects.get(pk=request.POST["confirm"])
            request_to_update.destination = request.POST["destination"]
            request_to_update.expected_arrival_time = request.POST["expected_arrival_time"]
            request_to_update.num_passengers = request.POST["num_passengers"]
            request_to_update.can_share = True if request.POST.get("can_share") == "on" else False
            request_to_update.vehicle_type = request.POST["vehicle_type"]
            request_to_update.special_request = request.POST["special_request"]
            request_to_update.save()
            selected_request = Request.objects.get(pk=request.POST["confirm"])
        else:
            selected_request = Request.objects.get(pk=request.POST["request_id"])
        return render(request, "ride_sharing/view_request_detail.html", {"request": selected_request, "cur_user": request.user})

@login_required
def edit_request_detail_owner(request):
    if request.method == "POST":
        request_info = Request.objects.get(pk=request.POST["request_id"])
        formatted_time = request_info.expected_arrival_time.astimezone().strftime('%Y-%m-%dT%H:%M')
        return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time})

@login_required
def edit_request_detail_sharer(request):
    if request.method == "POST":
        shareride_info = ShareRide.objects.get(booking=request.POST["request_id"], sharer=request.user) 

docker-deploy/web-app/ride_sharing/templates/base.html
<!doctype html>
<html lang="en">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'ride_sharing:homepage' %}">Ride Sharing</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto  mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a {% if "/my_requests/" in request.path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'ride_sharing:my_requests' %}">My Bookings</a>
          </li>
          <li class="nav-item">
            <a {% if "/place_request/" in request.path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'ride_sharing:place_request' %}">Book a New Ride</a>
          </li>
          <li class="nav-item">
            <a {% if "/sharer_search_for_open_request/" in request.path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'ride_sharing:sharer_search_for_open_request' %}">Share An Existing Ride</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if user.is_authenticated %}
              {% if not user.driver_set.all %}
              <li><a {% if "/driver_registration/" in request.path %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'ride_sharing:driver_registration' %}">Become a Driver</a></li>
              {% else %}
              <li class="nav-item dropdown">
                <a {% if "/driver_profile/" in request.path or "/driver_search_for_open_request/" in request.path or "/driver_view_confirmed_requests/" in request.path%}class="nav-link dropdown-toggle active"{% else %}class="nav-link dropdown-toggle"{% endif %} href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Driver Center
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'ride_sharing:driver_profile' %}">My Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'ride_sharing:driver_search_for_open_request' %}">Search for Open Requests</a></li>
                  <li><a class="dropdown-item" href="{% url 'ride_sharing:driver_view_confirmed_requests' %}">View Confirmed Rides</a></li>
                </ul>
              </li>
              {% endif %}
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button class="nav-link" type="submit">Log Out</button>
              </form>
            {% else %}
              <li><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
              <a class="nav-link" href="{% url 'ride_sharing:user_register' %}">Register</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Riding Sharing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == "error" %}
          <div class="alert alert-danger">
            {{ message }}
          </div>
          {% else %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% block content%} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>