docker-deploy/web-app/ride_sharing/urls.py
from django.urls import path

from . import views

app_name = "ride_sharing"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    #path("send_email_test/", views.send_email_test, name="send_email_test"),
    path("user_register/", views.user_register, name="user_register"),
    # user request related
    path("place_request/", views.place_request, name="place_request"),
    path("my_requests/", views.my_requests, name="my_requests"),
    path("view_request_detail", views.view_request_detail, name="view_request_detail"),
    path("edit_request_detail_owner", views.edit_request_detail_owner, name="edit_request_detail_owner"),
    path("edit_request_detail_sharer", views.edit_request_detail_sharer, name="edit_request_detail_sharer"),
    # driver related
    path("driver_view_confirmed_requests/", views.driver_view_confirmed_requests, name="driver_view_confirmed_requests"),
    path("driver_registration/", views.driver_registration, name="driver_registration"),
    path("driver_profile/", views.driver_profile, name="driver_profile"),
    path("edit_driver_profile/", views.edit_driver_profile, name="edit_driver_profile"),
    path("driver_registration_result/", views.driver_registration_result, name="driver_registration_result"),
    path("driver_search_for_open_request/", views.driver_search_for_open_request, name="driver_search_for_open_request"),
    # sharer related
    path("sharer_search_for_open_request/", views.sharer_search_for_open_request, name="sharer_search_for_open_request"),
]

docker-deploy/web-app/rideshare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("ride_sharing/", include("ride_sharing.urls")),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name="ride_sharing/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="ride_sharing/logout.html"), name="logout"),
]

docker-deploy/web-app/ride_sharing/models.py
import datetime

from django.conf import settings
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User

# Create your models here.
# class User(models.Model):
#     # email = models.CharField(max_length=200)
#     registration_date = models.DateTimeField("date registered")
#     def __str__(self):
#         return str(self.id)

class Driver(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    vehicle_type = models.CharField(max_length=200)
    license_plate_num = models.CharField(max_length=50)
    max_passenger_num = models.IntegerField()
    special_vehicle_info = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.name
    
class Request(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, models.SET_NULL, blank=True, null=True)
    destination = models.CharField(max_length=200)
    expected_arrival_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    num_passengers = models.IntegerField(default=1)
    vehicle_type = models.CharField(max_length=200, blank=True)
    special_request = models.TextField(blank=True)
    can_share = models.BooleanField()
    is_open = models.BooleanField()
    is_complete = models.BooleanField()
    def __str__(self):
        return self.destination

class ShareRide(models.Model):
    sharer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    booking = models.ForeignKey(Request, on_delete=models.CASCADE)
    num_sharer = models.IntegerField(default=1)
    def __str__(self):
        return self.sharer.username

docker-deploy/web-app/ride_sharing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

docker-deploy/web-app/ride_sharing/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum, Max
from django.core.mail import send_mail

from .forms import UserRegistrationForm
from .models import Driver, Request, ShareRide #, User 

@login_required
def homepage(request):
    return render(request, "ride_sharing/homepage.html")
    #return HttpResponse("Welcome to the ride sharing service! Click on the menu bar to continue")

def user_register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account Created for {username}. You can now log in")
            return redirect("login")
    else:   
        form = UserRegistrationForm()
    return render(request, "ride_sharing/user_register.html", {"form": form})

# @login_required
# def send_email(request):
#     send_mail(
#     "Subject here",
#     "Here is the message.",
#     "yhece568@yahoo.com",
#     ["aybucydu9@gmail.com"],
#     fail_silently=False,)
#     return HttpResponse("successfully sent email")
#    return render(request, "ride_sharing/place_request.html")

@login_required
def place_request(request):
    return render(request, "ride_sharing/place_request.html")

@login_required
def my_requests(request):
    if request.method == "POST":
        # sharer join a shared ride
        if request.POST.get("request_id_sharer_join"):
            try:
                existing_shareride = ShareRide.objects.get(sharer=request.user, booking=Request.objects.get(pk = int(request.POST["request_id_sharer_join"])))
                messages.error(request, f"You have already shared this ride before and can not join again. If you want to update your share request, please use the edit function!")
            except (KeyError, ShareRide.DoesNotExist):
                new_shareride = ShareRide(
                            sharer=request.user,
                            booking=Request.objects.get(pk = int(request.POST["request_id_sharer_join"])), 
                            num_sharer = request.POST["num_sharer"]
                            )
                new_shareride.save()
                share_destination = Request.objects.get(pk = int(request.POST["request_id_sharer_join"])).destination
                messages.success(request, f"Your Have successfully joined the shared ride to {share_destination}")

        # sharer cancle a shared ride    
        elif request.POST.get("cancel_ride_sharer"):
            shareride_to_delete = ShareRide.objects.get(booking=request.POST["cancel_ride_sharer"], sharer=request.user)
            shareride_to_delete.delete()
        
        # owner cancled a ride
        elif request.POST.get("cancel_ride"):
            request_to_delete = Request.objects.get(pk=request.POST["cancel_ride"])
            request_to_delete.delete()
        
        # place a new request
        else:
            # check input data validity
            if int(request.POST["num_passengers"]) < 1:
                messages.error(request, "Number of passenger can not be less than 1. Please correct your request info and place request again.")
                return render(request, "ride_sharing/place_request.html", {"current_data" : request.POST})
            elif int(request.POST["num_passengers"]) > 6:
                messages.error(request, "Number of passenger can not be more than 6. Please correct your request info and place request again.")
                return render(request, "ride_sharing/place_request.html", {"current_data" : request.POST})
            
            new_request = Request(owner=request.user, 
                            destination=request.POST["destination"], 
                            expected_arrival_time = request.POST["expected_arrival_time"],
                            num_passengers = request.POST["num_passengers"],
                            vehicle_type = request.POST["vehicle_type"],
                            special_request = request.POST["special_request"],
                            can_share = True if request.POST.get("can_share") == "on" else False,
                            is_open = True,
                            is_complete = False)
            new_request.save()
    
    # general - display request
    my_request_list = Request.objects.filter(owner=request.user) | Request.objects.filter(shareride__sharer=request.user)
    my_request_list = my_request_list.values("id", 
                                                "owner",
                                                "shareride__booking", 
                                                "destination", 
                                                "expected_arrival_time", 
                                                "num_passengers", 
                                                "can_share", 
                                                "is_open", 
                                                "is_complete").annotate(total_sharer = Sum("shareride__num_sharer"),
                                                                        total_pax = Sum("shareride__num_sharer") + Max("num_passengers"))
    my_request_list = my_request_list.exclude(is_complete=True).order_by("-expected_arrival_time")
    context = {"my_request_list": my_request_list, "cur_user": request.user}
    return render(request, "ride_sharing/my_requests.html", context)

@login_required
def view_request_detail(request):
    if request.method == "POST":
        # sharer edit ride details
        if request.POST.get("confirm_sharer"):
            if int(request.POST["num_sharer"]) < 1:
                messages.error(request, "Number of sharer can not be less than 1. Please correct your request info and place request again.")
                shareride_info = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user) 
                return render(request, "ride_sharing/edit_request_detail_sharer.html", 
                                        {"shareride_info": shareride_info,"current_data" : request.POST})
            elif int(request.POST["num_sharer"]) > 5:
                messages.error(request, "Number of sharer can not be more than 5. Please correct your request info and place request again.")
                shareride_info = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user) 
                return render(request, "ride_sharing/edit_request_detail_sharer.html", {"shareride_info": shareride_info,"current_data" : request.POST})

            shareride_to_update = ShareRide.objects.get(booking=request.POST["confirm_sharer"], sharer=request.user)
            shareride_to_update.num_sharer = request.POST["num_sharer"]
            shareride_to_update.save()
            selected_request = Request.objects.get(pk=request.POST["confirm_sharer"])
        # owner edit ride details
        elif request.POST.get("confirm"):
            if int(request.POST["num_passengers"]) < 1:
                messages.error(request, "Number of passengers can not be less than 1. Please correct your request info and place request again.")
                request_info = Request.objects.get(pk=request.POST["confirm"])
                formatted_time = request.POST["expected_arrival_time"]
                return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time, "current_data" : request.POST})
                
            elif int(request.POST["num_passengers"]) > 6:
                messages.error(request, "Number of passengers can not be more than 6. Please correct your request info and place request again.")
                request_info = Request.objects.get(pk=request.POST["confirm"])
                formatted_time = request.POST["expected_arrival_time"]
                return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time, "current_data" : request.POST})

            request_to_update = Request.objects.get(pk=request.POST["confirm"])
            request_to_update.destination = request.POST["destination"]
            request_to_update.expected_arrival_time = request.POST["expected_arrival_time"]
            request_to_update.num_passengers = request.POST["num_passengers"]
            request_to_update.can_share = True if request.POST.get("can_share") == "on" else False
            request_to_update.vehicle_type = request.POST["vehicle_type"]
            request_to_update.special_request = request.POST["special_request"]
            request_to_update.save()
            selected_request = Request.objects.get(pk=request.POST["confirm"])
        else:
            selected_request = Request.objects.get(pk=request.POST["request_id"])
        return render(request, "ride_sharing/view_request_detail.html", {"request": selected_request, "cur_user": request.user})

@login_required
def edit_request_detail_owner(request):
    if request.method == "POST":
        request_info = Request.objects.get(pk=request.POST["request_id"])
        formatted_time = request_info.expected_arrival_time.astimezone().strftime('%Y-%m-%dT%H:%M')
        return render(request, "ride_sharing/edit_request_detail_owner.html", 
                    {"request_info": request_info, "formatted_time": formatted_time})

@login_required
def edit_request_detail_sharer(request):
    if request.method == "POST":
        shareride_info = ShareRide.objects.get(booking=request.POST["request_id"], sharer=request.user) 

docker-deploy/web-app/ride_sharing/templates/ride_sharing/driver_profile.html
{% extends "base.html"%}
{% block content %}
{% if driver_info %}
<h1>My Profile</h1>
<table class="table">
    <thead>
      <tr>
        <th scope="col">name</th>
        <th scope="col">vehicle_type</th>
        <th scope="col">license_plate_num</th>
        <th scope="col">max_passenger_num</th>
        <th scope="col">special_vehicle_info</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ driver_info.name }}</td>
            <td>{{ driver_info.vehicle_type }}</td>
            <td>{{ driver_info.license_plate_num }}</td>
            <td>{{ driver_info.max_passenger_num }}</td>
            <td>{{ driver_info.special_vehicle_info }}</td>
            <form action="{% url 'ride_sharing:edit_driver_profile'%}" method="post">
              {% csrf_token %}
              <td><button type="submit" name="driver", value="{{driver_info.user}}", class="btn btn-primary btn-sm">Edit My Profile</button></td>
            </form>
        </tr>
    </tbody>
  </table>
{% else %}
    <p>You are not a driver yet.</p>
{% endif %}
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/driver_registration.html
{% extends "base.html"%}
{% block content %}
<div class="mb-3">
    <legend> Register to be a driver </legend>
</div>
<form action="{% url 'ride_sharing:driver_registration_result'%}" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="your_name" class="form-label">Full Name</label>
      <input type="text" class="form-control" id="your_name" name="your_name" required>
    </div>
    <div class="mb-3">
      <label for="vehicle_type" class="form-label">Your Vehicle Type</label>
      <input type="text" class="form-control" id="vehicle_type" name="vehicle_type" required>
    </div>
    <div class="mb-3">
        <label for="license_plate_num" class="form-label">Your License Plate Number</label>
        <input type="text" class="form-control" id="license_plate_num" name="license_plate_num" required>
    </div>
    <div class="mb-3">
    <label for="max_passenger_num" class="form-label">Max Passenger Number</label>
    <input type="text" class="form-control" id="max_passenger_num" name="max_passenger_num" required>
    </div>
    <div class="mb-3">
        <label for="special_vehicle_info" class="form-label">Special Vehicle Information</label>
        <input type="text" class="form-control" id="special_vehicle_info" name="special_vehicle_info">
    </div>
    <button type="submit" value="OK" class="btn btn-primary">Register Me</button>
  </form>
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/driver_view_confirmed_requests.html
{% extends "base.html"%}
{% block content %}
<h3>My Confirmed Rides</h3>
{% if my_request_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Destnation</th>
        <th scope="col">Arrival Time</th>
        <th scope="col">Number of Passengers</th>
        <th scope="col">Number of Sharer</th>
        <th scope="col">Total Riders</th>
        <th scope="col">Ride Detail</th>
        <th scope="col">Mark as Complete</th>
      </tr>
    </thead>
    <tbody>
      {% for request in my_request_list %}
        <tr>
            {% if request.total_sharer %}
              <td><button class="btn btn-danger btn-sm" style="pointer-events: none;">Shared Ride</button></td>
            {% else %}
              <td></td>
            {% endif %}
            <td>{{ request.destination }}</td>
            <td>{{ request.expected_arrival_time }}</td>
            <td>{{ request.num_passengers }}</td>
            {% if request.total_sharer %}
              <td>{{ request.total_sharer }}</td>
            {% else %}
              <td>0</td>
            {% endif %}
            {% if request.total_sharer %}
              <td>{{ request.total_pax }}</td>
            {% else %}
              <td>{{ request.num_passengers }}</td>
            {% endif %}
            {% if request.is_complete %}
              <td><a href="{% url 'ride_sharing:view_request_detail'%}">completed</a></td>
            {% else %}
              <form action="{% url 'ride_sharing:view_request_detail'%}" method="post">
                {% csrf_token %}
                  <td>
                    <button type="submit" name="request_id", value="{{request.id}}", class="btn btn-link">see more</button>
                  </td>
              </form>
              <form action="{% url 'ride_sharing:driver_view_confirmed_requests'%}" method="post">
                {% csrf_token %}
                  <td>
                    <button type="submit" name="complete_request_id", value="{{request.id}}", class="btn btn-primary btn-sm">Complete Ride</button>
                  </td>
              </form>
            {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
    <p>You don't have any confirmed rides right now. You can claim more rides via the Search for Open Requests section.</p>
{% endif %}
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/edit_driver_profile.html
{% extends "base.html"%}
{% block content %}
<div class="mb-3">
    <legend> Edit Driver Profile</legend>
</div>
<form action="{% url 'ride_sharing:driver_profile'%}" method="post">
    {% csrf_token %}
    {% if current_data %}
    <div class="mb-3">
      <label for="your_name" class="form-label">Full Name</label>
      <input type="text" class="form-control" id="your_name" name="your_name" value="{{current_data.your_name}}" required>
    </div>
    <div class="mb-3">
      <label for="vehicle_type" class="form-label">Your Vehicle Type</label>
      <input type="text" class="form-control" id="vehicle_type" name="vehicle_type" value="{{current_data.vehicle_type}}" required>
    </div>
    <div class="mb-3">
        <label for="license_plate_num" class="form-label">Your License Plate Number</label>
        <input type="text" class="form-control" id="license_plate_num" name="license_plate_num" value="{{current_data.license_plate_num}}" required>
    </div>
    <div class="mb-3">
    <label for="max_passenger_num" class="form-label">Max Passenger Number</label>
    <input type="text" class="form-control" id="max_passenger_num" name="max_passenger_num" value="{{current_data.max_passenger_num}}" required>
    </div>
    <div class="mb-3">
        <label for="special_vehicle_info" class="form-label">Special Vehicle Information</label>
        <input type="text" class="form-control" id="special_vehicle_info" name="special_vehicle_info" value="{{current_data.special_vehicle_info}}">
    </div>
    {% else %}
    <div class="mb-3">
      <label for="your_name" class="form-label">Full Name</label>
      <input type="text" class="form-control" id="your_name" name="your_name" value="{{driver_info.name}}" required>
    </div>
    <div class="mb-3">
      <label for="vehicle_type" class="form-label">Your Vehicle Type</label>
      <input type="text" class="form-control" id="vehicle_type" name="vehicle_type" value="{{driver_info.vehicle_type}}" required>
    </div>
    <div class="mb-3">
        <label for="license_plate_num" class="form-label">Your License Plate Number</label>
        <input type="text" class="form-control" id="license_plate_num" name="license_plate_num" value="{{driver_info.license_plate_num}}" required>
    </div>
    <div class="mb-3">
    <label for="max_passenger_num" class="form-label">Max Passenger Number</label>
    <input type="text" class="form-control" id="max_passenger_num" name="max_passenger_num" value="{{driver_info.max_passenger_num}}" required>
    </div>
    <div class="mb-3">
        <label for="special_vehicle_info" class="form-label">Special Vehicle Information</label>
        <input type="text" class="form-control" id="special_vehicle_info" name="special_vehicle_info" value="{{driver_info.special_vehicle_info}}">
    </div>
    {% endif %}
    <button type="submit" name="confirm" value="OK" class="btn btn-primary">Save Edits</button>
    <button type="submit" value="cancle" class="btn btn-outline-secondary">Cancle Edits</button>
  </form>
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/edit_request_detail_owner.html
{% extends "base.html"%}
{% block content %}
<div class="mb-3">
    <legend> Place a Ride Request </legend>
</div>
<div class="p-2">
<form action="{% url 'ride_sharing:view_request_detail'%}" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="destination" class="form-label">Destination Address</label>
      {% if current_data %}
        <input type="text" class="form-control" id="destination" name="destination" value="{{current_data.destination}}" required>
      {% else %}
        <input type="text" class="form-control" id="destination" name="destination" value="{{request_info.destination}}" required>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="expected_arrival_time" class="form-label">expected_arrival_time</label>
        <input type="datetime-local" class="form-control" id="expected_arrival_time" name="expected_arrival_time" value="{{formatted_time}}" required>
    </div>
    <div class="mb-3">
        <label for="num_passengers" class="form-label">num_passengers</label>
        {% if current_data %}
          <input type="number" class="form-control" id="num_passengers" name="num_passengers" value="{{current_data.num_passengers}}" required>
        {% else %}
          <input type="number" class="form-control" id="num_passengers" name="num_passengers" value="{{request_info.num_passengers}}" required>
        {% endif %}
    </div>
    {% if current_data%}
    {% if current_data.can_share%}
      <div class="mb-3">
          <input type="checkbox" id="can_share" name="can_share" checked>
          <label for="can_share" class="form-label"> I'm open to having other passengers join me on this ride</label>
      </div>
    {% else %}
      <div class="mb-3">
        <input type="checkbox" id="can_share" name="can_share">
        <label for="can_share" class="form-label"> I'm open to having other passengers join me on this ride</label>
      </div>
    {% endif %}
    {% else %}
      {% if request_info.can_share%}
        <div class="mb-3">
            <input type="checkbox" id="can_share" name="can_share" checked>
            <label for="can_share" class="form-label"> I'm open to having other passengers join me on this ride</label>
        </div>
      {% else %}
        <div class="mb-3">
          <input type="checkbox" id="can_share" name="can_share">
          <label for="can_share" class="form-label"> I'm open to having other passengers join me on this ride</label>
        </div>
      {% endif %}
    {% endif %}
    <div class="mb-3">
    <label for="vehicle_type" class="form-label">vehicle_type (Optional)</label>
    {% if current_data %}
    <input type="text" class="form-control" id="vehicle_type" name="vehicle_type" value="{{current_data.vehicle_type}}">
    {% else %}
    <input type="text" class="form-control" id="vehicle_type" name="vehicle_type" value="{{request_info.vehicle_type}}">
    {% endif %}
    </div>
    <div class="mb-3">
        <label for="special_request" class="form-label">special_request (Optional)</label>
        {% if current_data %}
        <input type="text" class="form-control" id="special_request" name="special_request" value="{{current_data.special_request}}">
        {% else %}
        <input type="text" class="form-control" id="special_request" name="special_request" value="{{request_info.special_request}}">
        {% endif %}
    </div>
    <button type="submit" name="confirm" value="{{request_info.id}}" class="btn btn-primary">Save Edits</button>
    <button type="submit" name="request_id" value="{{request_info.id}}" class="btn btn-outline-secondary">Cancle Edits</button>
  </form>
</div>
<div class="p-2">
  <form action="{% url 'ride_sharing:my_requests'%}" method="post">
    {% csrf_token %}
    <button type="submit" name="cancel_ride" value="{{request_info.id}}" class="btn btn-danger">Cancle Ride</button>
  </form>
</div>
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/edit_request_detail_sharer.html
{% extends "base.html"%}
{% block content %}
<div class="mb-3">
    <legend> Edit My Share Ride </legend>
</div>
<div class="p-2">
<form action="{% url 'ride_sharing:view_request_detail'%}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="num_sharer" class="form-label">num_sharer</label>
        {% if current_data %}
        <input type="number" class="form-control" id="num_sharer" name="num_sharer" value="{{current_data.num_sharer}}" required>
        {% else %}
        <input type="number" class="form-control" id="num_sharer" name="num_sharer" value="{{shareride_info.num_sharer}}" required>
        {% endif %}
    </div>
    <button type="submit" name="confirm_sharer" value="{{shareride_info.booking.id}}" class="btn btn-primary">Save Edits</button>
    <button type="submit" name="request_id" value="{{shareride_info.booking.id}}" class="btn btn-outline-secondary">Cancle Edits</button>
  </form>
</div>
<div class="p-2">
  <form action="{% url 'ride_sharing:my_requests'%}" method="post">
    {% csrf_token %}
    <button type="submit" name="cancel_ride_sharer" value="{{shareride_info.booking.id}}" class="btn btn-danger">Cancle Share Ride</button>
  </form>
</div>
{% endblock content %}

docker-deploy/web-app/ride_sharing/templates/ride_sharing/view_request_detail.html
{% extends "base.html"%}
{% block content %}
{% if request %}
<div>
  <h3>Request Details</h3>
</div>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Ride Owner</th>
        <th scope="col">Destnation</th>
        <th scope="col">Arrival Time</th>
        <th scope="col">Number of Passengers</th>
        <th scope="col">Sharable with others</th>
        <th scope="col">vehicle_type</th>
        <th scope="col">special_request</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ request.owner }}</td>
            <td>{{ request.destination }}</td>
            <td>{{ request.expected_arrival_time }}</td>
            <td>{{ request.num_passengers }}</td>
            <td>{{ request.can_share }}</td>
            <td>{{ request.vehicle_type }}</td>
            <td>{{ request.special_request }}</td>
            {% if request.is_open %}
                <td>open</td>
            {% elif request.is_complete  == False %}
                <td>confirmed</td>
            {% else %}
            <td>completed</td>
            {% endif %}
        </tr>
    </tbody>
  </table>
  {% if request.can_share == True %}
    <div>
      <h3>Sharer Info</h3>
    </div>
    {% if request.shareride_set.all %}
      <div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Sharer</th>
              <th scope="col">Number of Sharer</th>
            </tr>
          </thead>
          <tbody>
            {% for shareride in request.shareride_set.all %}
              <tr>
                    <td>{{ shareride.sharer }}</td>  
                    <td>{{ shareride.num_sharer }}</td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <td>No sharer has joined your request yet</td> 
    {% endif %}
  {% endif %}
  {% if request.is_open == False %}
    <div>
      <h3>Driver Info</h3>
    </div>
      <div>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th>vehicle_type</th>
              <th>license_plate_num</th>
              <th>special_vehicle_info</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                    <td>{{ request.driver.name }}</td>  
                    <td>{{ request.driver.vehicle_type }}</td>
                    <td>{{ request.driver.license_plate_num }}</td>
                    <td>{{ request.driver.special_vehicle_info }}</td>
              </tr>
          </tbody>
        </table>
      </div>
  {% endif %}
{% else %}
    <p>No requests are available.</p>
{% endif %}

{% if request.is_open and request.owner.id == cur_user.id%}
<div class="p-2">
  <form action="{% url 'ride_sharing:edit_request_detail_owner'%}" method="post">
    {% csrf_token %}
      <button type="submit" name="request_id", value="{{request.id}}", class="btn btn-primary">Edit Ride</button>
  </form>
</div>
<div class="p-2">
  <form action="{% url 'ride_sharing:my_requests'%}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <button type="submit" name="cancel_ride" value="{{request.id}}" class="btn btn-danger">Cancle Ride</button>
    </div>
  </form>
</div>
{% endif %}
{% for share in request.shareride_set.all %}
  {% if request.is_open and request.owner.id != cur_user.id and cur_user.id == share.sharer.id%}
  <div class="p-2">
    <form action="{% url 'ride_sharing:edit_request_detail_sharer'%}" method="post">
      {% csrf_token %}
        <button type="submit" name="request_id", value="{{request.id}}", class="btn btn-primary">Edit Share Ride</button>
    </form>
  </div>
  <div class="p-2">
    <form action="{% url 'ride_sharing:my_requests'%}" method="post">
      {% csrf_token %}
      <button type="submit" name="cancel_ride_sharer" value="{{request.id}}" class="btn btn-danger">Cancle Share Ride</button>
    </form>
  </div>
  {% endif %}
{% endfor %}

{% endblock content %}